FORMAT: 1A
HOST: http://meteorite-landings.me/

# Meteorites

Meteorites is an API for information on meteorites that have landed on Earth as well as their classifications and countries.
# Group Meteorites

## Meteorites Collection [/meteorites]
### Get a list of all meteorites [GET]

+ Response 200 (application/json)
        
        [
            {
                "name" : "Ensisheim",
                "meteor_id" : "1",
                "mass" : "127000",
                "country" :
                    {
                        "name" : "France"
                    },
                "class" :
                    {
                        "name" : "LL6",
                        "classification_id": "1"
                     },
                "year" : "1492"
                "longitude" : "7.350000",
                "latitude" : "47.866670"
            },
            {
                "name" : "Thika",
                "meteor_id" : "2",
                "mass" : "14200",
                "country" :
                    {
                        "name" : "Kenya"
                    },
                "class" :
                    {
                        "name" : "L6",
                        "classification_id": "2"
                     },
                "year" : "2011"
                "longitude" : "37.150280",
                "latitude" : "-1.002780"
            },
            {
                "name" : "Bunburra Rockhole",
                "meteor_id" : "3",
                "mass" : "324",
                "country" :
                    {
                        "name" : "Australia"
                    },
                "class" :
                    {
                        "name" : "Eucrite",
                        "classification_id": "3"
                     },
                "year" : "2007"
                "longitude" : "129.190000",
                "latitude" : "-31.350000"
            }
        ]

## Single Meteor [/meteorites/{meteor_id}]

+ Parameters 
    + meteor_id (number) - Unique id of the meteor requested
    
### Get information about a specific meteor [GET]

+ Response 200 (application/json)
        
        {
            "name" : "Ensisheim",
            "meteor_id" : "1",
            "mass" : "127000",
            "country" :
                {
                    "name" : "France"
                },
            "class" :
                {
                    "name" : "LL6",
                    "classification_id": "1"
                 },
            "year" : "1492"
            "longitude" : "7.350000",
            "latitude" : "47.866670"
        }

# Group Classes

## Classes Collection [/classes]
### Get a list of all classes [GET]

+ Response 200 (application/json)
        
        [
            {
                "name": "LL6",
                "classification_id": "1",
                "class_ID": "Chondrite",
                "compositional_Type": "Stony",
                "parent_Body": "Unknown"
                "number_Found": "1"
                "meteorites": 
                    [
                        {"name": "Ensisheim",
                        "meteor_id": "1"
                        }
                    ]
            },
            {
                "name": "L6",
                "classification_id": "2",
                "class_ID": "Chondrite",
                "compositional_Type": "Stony",
                "parent_Body": "Flora Family"
                "number_Found": "1"
                "meteorites": 
                    [
                        {"name": "Thika",
                        "meteor_id": "2"
                        }
                    ]
            },
            {
                "name": "Eucrite",
                "classification_id": "3",
                "class_ID": "Achondrite",
                "compositional_Type": "Stony",
                "parent_Body": "Asteroid 4 Vesta"
                "number_Found": "1"
                "meteorites": 
                    [
                        {"name": "Bunburra Rockhole",
                        "meteor_id": "3"
                        }
                    ]
            }
        ]


## Single Class [/classes/{classification_id}]

+ Parameters 
    + classification_id (number) - Unique id of the class requested

### Get information about a specific class [GET]

+ Response 200 (application/json)
        
        {
                "name": "LL6",
                "classification_id": "1",
                "class_ID": "Chondrite",
                "compositional_Type": "Stony",
                "parent_Body": "Unknown"
                "number_Found": "1"
                "meteorites": 
                    [
                        {"name": "Ensisheim",
                        "meteor_id": "1"
                        }
                    ]
            }

# Group Countries

## Countries Collection [/countries]
### Get a list of all countries where a meteor has fallen [GET]

+ Response 200 (application/json)
        
        [
            {
                "name": "Australia",
                "country_id": "1",
                "area": "7692024",
                "centroid": "n/a",
                "number_found": "1",
                "meteorites": 
                    [
                        {"name" : "Bunburra Rockhole",
                        "meteor_id" : "3"
                        }
                    ]
            },
            {
                "name": "France",
                "country_id": "2",
                "area": "643801",
                "centroid": "n/a",
                "number_found": "1",
                "meteorites": 
                    [
                        {"name" : "Ensisheim",
                        "meteor_id" : "1"
                        }
                    ]
            },
            {
                "name": "Kenya",
                "country_id": "3",
                "area": "581309",
                "centroid": "n/a",
                "number_found": "1",
                "meteorites": 
                    [
                        {"name" : "Thika",
                        "meteor_id" : "2"
                        }
                    ]
            }
        ]


## Single Country [/countries/{country_id}]

+ Parameters 
    + country_id (number) - Unique id of the country requested

### Get information about a specific country [GET]

+ Response 200 (application/json)
        
        {
                "name": "Australia",
                "country_id": "1",
                "area": "7692024",
                "centroid": "n/a",
                "number_found": "1",
                "meteorites": 
                    [
                        {"name" : "Bunburra Rockhole",
                        "meteor_id" : "3",
                        }
                    ]
            },